name: AWS Secrets Manager
description: Read secrets from AWS Secrets Manager
author: https://github.com/seek-oss
requirements:
  - docker
  - jq
configuration:
  properties:
    env:
      type: object
    file:
      type: array
    json-to-env:
      type: array
    endpoint-url:
      type: string
  required: []
